-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "{{colors.surface.default.hex}}",
  base01 = "{{colors.surface_container_low.default.hex}}",
  base02 = "{{colors.surface_container.default.hex}}",
  base03 = "{{colors.outline.default.hex}}",
  base04 = "{{colors.on_surface_variant.default.hex}}",
  base05 = "{{colors.on_surface.default.hex}}",
  base06 = "{{colors.surface_bright.default.hex}}",
  base07 = "{{colors.on_primary_container.default.hex}}",

  base08 = "{{colors.tertiary.default.hex | lighten: -5}}",
  base09 = "{{colors.tertiary.default.hex | lighten: 10}}",
  base0A = "{{colors.secondary.default.hex | lighten: 10}}",
  base0B = "{{colors.primary.default.hex | lighten: 10}}",
  base0C = "{{colors.tertiary.default.hex}}",
  base0D = "{{colors.primary.default.hex}}",
  base0E = "{{colors.secondary.default.hex}}",
  base0F = "{{colors.secondary.default.hex | lighten: -10}}",
})

-- base16-colorscheme automatically sets vim.g.terminal_color_x variables.
-- We wipe them out so Neovim defaults to its standard internal ANSI palette.
for i = 0, 15 do
  vim.g['terminal_color_' .. i] = nil
end

-- After theming base16, we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
set_hl_mutliple({ 'Normal', 'NormalNC' }, {
  bg = 'none',
})

-- Make selected text stand out more
set_hl_mutliple({ 'Visual' }, {
  bg = '{{colors.primary_container.default.hex}}',
  fg = '{{colors.on_primary_container.default.hex}}', -- normal text contrast
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '{{colors.outline.default.hex}}',
  italic = true,
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary.default.hex}}',
})

-- Make string text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
  fg = '{{colors.tertiary.default.hex | lighten: -25.0 }}',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '{{colors.secondary.default.hex}}',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '{{colors.inverse_primary.default.hex | lighten: 10.0 }}',
})

set_hl_mutliple({ "MsgArea" }, {
  bg = '{{colors.surface_container_lowest.default.hex}}',
  fg = '{{colors.primary.default.hex}}',
})

-- Tweak the display of matching pairs like (), [], {}
set_hl_mutliple({ "MatchParen" }, {
  bg = '#2a2a2a', -- very subtle
  underline = true,
  sp = '{{colors.primary.default.hex}}',
})
