-- Generated by Matugen
-- Matugen → Base16 mapping (dark scheme)
require('base16-colorscheme').setup({
  base00 = "{{colors.background.default.hex}}", -- Background
  base01 = "{{colors.surface_container_lowest.default.hex}}",
  base02 = "{{colors.surface_container_low.default.hex}}",
  base03 = "{{colors.outline_variant.default.hex}}",    -- Comments, subtle UI (lighter!)
  base04 = "{{colors.on_surface_variant.default.hex}}", -- Dim text / less focus
  base05 = "{{colors.on_surface.default.hex}}",         -- Normal text
  base06 = "{{colors.inverse_on_surface.default.hex}}", -- Brighter text
  base07 = "{{colors.surface_bright.default.hex}}",     -- Brightest UI contrast

  base08 = "{{colors.error.default.hex}}",
  base09 = "{{colors.tertiary.default.hex}}",
  base0A = "{{colors.secondary.default.hex}}",
  base0B = "{{colors.primary.default.hex}}",
  base0C = "{{colors.tertiary_container.default.hex}}",
  base0D = "{{colors.primary_container.default.hex}}",
  base0E = "{{colors.secondary_container.default.hex}}",
  base0F = "{{colors.error_container.default.hex}}",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.outline.default.hex}}',
  fg = '{{colors.background.default.hex}}', -- normal text contrast
})

set_hl({ 'TSComment', 'Comment' }, {
  fg = '{{colors.secondary_fixed_dim.default.hex}}',
})

set_hl({ 'TSMethod', 'Method' }, {
  fg = '{{colors.tertiary.default.hex}}',
})

set_hl({ 'TSFunction', 'Function' }, {
  fg = '{{colors.secondary.default.hex}}',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '{{colors.inverse_primary.default.hex}}',
})

require('lualine').setup()
